---
- name: Install MySQL and OpenJDK on localhost
  hosts: ec2-18-219-226-149.us-east-2.compute.amazonaws.com
  become: yes

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install MySQL server
      package:
        name: mysql-server
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

    - name: Install OpenJDK
      package:
        name: openjdk-11-jdk  # Adjust version as needed
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
